export type FretboardPreset = {
	name: string;
	selectedInstrument: string;
	selectedKey: string;
	lowestNote: string;
	stringRangeStart: number;
	stringRangeEnd: number;
	fretRangeStart: number;
	fretRangeEnd: number;
	anchorModeEnabled: boolean;
	anchorDegree: number;
	anchorFrequency: number;
	sequenceModeEnabled?: boolean;
	sequenceInput?: string;
	sequenceFrequency?: number;
	sequenceQuestionCount?: number;
	highlightedDegrees: number[];
	showNoteNameOnDot?: boolean;
	redDotDisplayMode?: 'degrees' | 'notes' | 'empty';
	showRedDotsOnSelectedStringOnly?: boolean;
	selectedRedDotStrings?: number[];
	showFragmentDots?: boolean;
	showFragmentDegrees?: boolean;
	gameMode?: 'find-degree' | 'find-note';
	autoNextEnabled?: boolean;
	autoNextDelay?: number;
	autoPlayOnNewQuestion?: boolean;
	showLastPositionDegree?: boolean;
};
